version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  dash:
    build:
      context: .
      dockerfile: Dockerfile.dash
    container_name: dash_dash
    command: python app.py
    volumes:
    - .:/code
    ports:
    - "80:8080"
    depends_on:
    - db

  jupyterlab:
    networks:
      - mlflow-net
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    working_dir: "/container-notebooks"
    volumes:
      - ./notebooks:/container-notebooks
      - ./answers:/container-answers
    expose:
      - 8888
    ports:
      - 8991:8888
networks:
  mlflow-net:

volumes:
  my-db:
