version: '3'
services:
  jupyterlab:
    networks:
      - mlflow-net
    build:
      context: .
      dockerfile: ../infra/Dockerfile.jupyter
    working_dir: "/container-notebooks"
    volumes:
      - ./notebooks:/container-notebooks
      - ./answers:/container-answers
    expose:
      - 8888
    ports:
      - 8991:8888
networks:
  mlflow-net: